import { NewsArticle, MarketTrend, IndustryTrend, AIUpdate, StartupOpportunity } from './types';

export const MOCK_NEWS: NewsArticle[] = [
  {
    id: '1',
    title: 'Global Semiconductor Shortage Approaches Resolution',
    summary: 'Major chip manufacturers announce record output, signaling an end to the multi-year supply chain crisis.',
    category: 'Technology',
    isHighImpact: true,
    timestamp: '2h ago',
    source: 'Tech Daily',
    location: 'Hsinchu Science Park, Taiwan',
    coordinates: { lat: 24.7821, lng: 120.9928 },
    sceneDetails: 'Inside TSMC Fab 18, massive automated crane systems are moving cleanroom pods across the ceiling in a choreographed mechanical ballet.',
    newsPoint: 'Production yield exceeds 98% for 2nm process',
    isLive: true,
    relatedTrend: { symbol: 'TSE:2330', price: 812.50, change: 2.1, volume: 45200, marketData: 'Global Semiconductor Index: +1.4%' }
  },
  {
    id: '2',
    title: 'Central Banks Signal Potential Rate Cuts',
    summary: 'Economic indicators suggest inflation is stabilizing, leading to discussions about easing monetary policy.',
    category: 'Business',
    isHighImpact: true,
    timestamp: '4h ago',
    source: 'Finance Times',
    location: 'ECB Headquarters, Frankfurt',
    coordinates: { lat: 50.1109, lng: 8.6821 },
    sceneDetails: 'Top economists seen descending the grand staircase of the Eurotower after a 14-hour marathon session of the Governing Council.',
    newsPoint: 'Core inflation drops to 2.4% annually',
    isLive: false,
    relatedTrend: { symbol: 'EUR/USD', price: 1.0854, change: -0.12, volume: 120000, marketData: 'Bond Yields: -15bps' }
  },
  {
    id: '3',
    title: 'Deep Sea Biodiversity Treaty Signed',
    summary: 'Over 100 nations agree on a legal framework to protect international waters.',
    category: 'Environment',
    isHighImpact: false,
    timestamp: '5h ago',
    source: 'Green Planet',
    location: 'UN HQ, Nairobi',
    coordinates: { lat: -1.2921, lng: 36.8219 },
    sceneDetails: 'Delegates from island nations seen embracing on the assembly floor as the High Seas Treaty finally passed with unanimous support.',
    isLive: false,
  },
  {
    id: '4',
    title: 'AI Governance Act Passed',
    summary: 'New regulations set strict guidelines for high-risk AI deployments while encouraging innovation.',
    category: 'Politics',
    isHighImpact: true,
    timestamp: '6h ago',
    source: 'Global Policy',
    location: 'European Parliament, Brussels',
    coordinates: { lat: 50.8503, lng: 4.3517 },
    sceneDetails: 'The central voting board illuminates in green as the final tally confirms the world\'s first comprehensive AI regulation framework.',
    newsPoint: 'Unanimous vote for Article 42 on biometric surveillance',
    isLive: true,
    relatedTrend: { symbol: 'NASDAQ:AI', price: 34.20, change: -1.5, volume: 32000, marketData: 'Tech Volatility Index: 18.5' }
  },
  {
    id: '5',
    title: 'Solid-State Battery Breakthrough',
    summary: 'A startup emerges with a prototype that could redefine electric vehicle autonomy.',
    category: 'Technology',
    isHighImpact: true,
    timestamp: '8h ago',
    source: 'Autotech',
    location: 'Lucid Motors R&D, Newark, CA',
    coordinates: { lat: 37.5297, lng: -122.0402 },
    sceneDetails: 'A prototype battery pack undergoing rigorous thermal cycle testing, glowing faintly on telemetry monitors in the high-voltage lab.',
    newsPoint: 'Energy density reached 450 Wh/kg in testing',
    isLive: true,
    relatedTrend: { symbol: 'LCID', price: 4.85, change: 12.4, volume: 156000, marketData: 'EV Sector: +4.2%' }
  },
  {
    id: '6',
    title: 'E-commerce Giants Pivot to O2O Models',
    summary: 'Market shifts show consumers returning to physical retail with a digital-first approach.',
    category: 'Business',
    isHighImpact: false,
    timestamp: '10h ago',
    source: 'Retail Insider',
    location: 'Shibuya Crossing, Tokyo',
    coordinates: { lat: 35.6595, lng: 139.7005 },
    sceneDetails: 'A massive new "Amazon Fresh" flagship store, displaying live inventory levels on high-contrast window displays to passing crowds.',
    isLive: false,
  },
  {
    id: '7',
    title: 'Urban Heat Island Management Priority',
    summary: 'New architectural guidelines mandate reflective surfaces and vertical forests.',
    category: 'Environment',
    isHighImpact: false,
    timestamp: '12h ago',
    source: 'Nature News',
    location: 'Marina Bay Sands Area, Singapore',
    coordinates: { lat: 1.2838, lng: 103.8591 },
    sceneDetails: 'Construction drones installing solar-reflective tiles on a 70-story residential spire already draped in lush vertical gardens.',
    isLive: false,
  },
  {
    id: '8',
    title: 'Tax Reforms for Freelance Platforms',
    summary: 'New legislation aims to provide social security benefits to gig workers.',
    category: 'Politics',
    isHighImpact: false,
    timestamp: '1d ago',
    source: 'Law Review',
    location: 'Capitol Hill, Washington D.C.',
    coordinates: { lat: 38.8899, lng: -77.0091 },
    sceneDetails: 'Small groups of gig workers gathered outside the Rayburn building, holding umbrellas in the rain as the committee markup session concluded.',
    isLive: false,
  },
  {
    id: '9',
    title: 'Open Source LLM Competes with Proprietary',
    summary: 'Latest community model shows parity with top-tier commercial LLMs in coding.',
    category: 'Technology',
    isHighImpact: true,
    timestamp: '1d ago',
    source: 'AI Hub',
    location: 'Hacker Hotel, San Francisco',
    coordinates: { lat: 37.7749, lng: -122.4194 },
    sceneDetails: 'Dozens of monitors in a communal workspace showing rolling benchmark results as the 70B parameter model completes its evaluation.',
    isLive: true,
  },
  {
    id: '10',
    title: 'Solar Prices Hit Historic Lows',
    summary: 'Large-scale solar installations are now cheaper than existing coal-fired power plants.',
    category: 'Environment',
    isHighImpact: true,
    timestamp: '1d ago',
    source: 'Energy Weekly',
    location: 'Bhadla Solar Park, India',
    coordinates: { lat: 27.5395, lng: 72.3789 },
    sceneDetails: 'Miles of photovoltaic panels stretching into the horizon of the Thar desert, shimmering under the midday sun as they feed 2GW into the grid.',
    newsPoint: 'Cost per Watt falls below $0.10 for first time',
    isLive: true,
    relatedTrend: { symbol: 'PV-IDX', price: 0.12, change: -5.4, volume: 88000, marketData: 'Energy Commodities: -2.1%' }
  },
  {
    id: '11',
    title: 'OpenAI Proposes 32-Hour Work Week to Boost AI Productivity',
    summary: 'The AI leader suggests that reduced working hours could lead to higher cognitive performance and creative breakthroughs in model development.',
    category: 'Technology',
    isHighImpact: true,
    timestamp: '15m ago',
    source: 'Tech Daily',
    location: 'OpenAI HQ, San Francisco',
    coordinates: { lat: 37.7624, lng: -122.4148 },
    sceneDetails: 'Engineers in the Mission District office seen collaborating in the early afternoon, transitioning to new "deep-focus" schedules designed for peak output.',
    newsPoint: 'Internal memo suggests 15% increase in creative throughput',
    isLive: true,
    relatedTrend: { symbol: 'MSFT', price: 425.20, change: 0.8, volume: 12000, marketData: 'Nasdaq 100: +0.5%' }
  },
  {
    id: '12',
    title: 'Critical Cybersecurity Alert: Samsung and Gmail Users Targeted',
    summary: 'Major security agencies issue warnings regarding zero-day vulnerabilities in mobile hardware and global email services.',
    category: 'Technology',
    isHighImpact: true,
    timestamp: '45m ago',
    source: 'Cyber Defense',
    location: 'Global Security Ops',
    coordinates: { lat: 38.9339, lng: -77.2638 },
    sceneDetails: 'Activity spikes in SOC centers globally as white-hat hackers demonstrate the exploit chain involving memory corruption in shared libraries.',
    newsPoint: 'Over 200 million devices estimated at risk',
    isLive: true,
    relatedTrend: { symbol: 'GOOGL', price: 172.50, change: -1.2, volume: 25000, marketData: 'Cybersecurity Index: +3.8%' }
  },
  {
    id: '13',
    title: 'Sirius XM and iHeartMedia In Potential Merger Talks',
    summary: 'The potential $15B tie-up would create a dominant force in audio broadcasting and podcasting to compete with streaming giants.',
    category: 'Business',
    isHighImpact: true,
    timestamp: '2h ago',
    source: 'Media Watch',
    location: 'Midtown Manhattan, NY',
    coordinates: { lat: 40.7589, lng: -73.9851 },
    sceneDetails: 'Stock tickers in Times Square flashing both company names as analysts debate the antitrust implications of an audio monopoly.',
    newsPoint: 'Combined user base would reach 110 million monthly actives',
    isLive: false,
    relatedTrend: { symbol: 'SIRI', price: 3.45, change: 8.5, volume: 450000, marketData: 'Media & Ent: +1.2%' }
  },
  {
    id: '14',
    title: 'Infrastructure Investments Surge Amid AI Boom',
    summary: 'Investors pour record capital into power grids and specialized data centers to support the next generation of generative AI models.',
    category: 'Business',
    isHighImpact: true,
    timestamp: '4h ago',
    source: 'Forbes',
    location: 'Northern Virginia Data Center Alley',
    coordinates: { lat: 39.0438, lng: -77.4875 },
    sceneDetails: 'Multiple 100MW substations under construction near Ashburn, with high-voltage cooling systems being airlifted into place.',
    newsPoint: 'Vacancy rates for Tier-3 data centers hit record low of 1.2%',
    isLive: false,
    relatedTrend: { symbol: 'EQIX', price: 845.00, change: 3.2, volume: 5500, marketData: 'Real Estate REITS: +2.1%' }
  },
];

export const MOCK_MARKETS: MarketTrend[] = [
  {
    symbol: 'NIFTY 50',
    name: 'NSE India Index',
    price: 22450.50,
    change: 1.25,
    volume: 852400,
    marketCap: '₹145.2T',
    peRatio: 22.4,
    range52w: { low: 18837, high: 22526 },
    open: 22210.15,
    high: 22485.60,
    low: 22180.45,
    history: [
      { time: '09:30', value: 22100, volume: 450 },
      { time: '10:30', value: 22200, volume: 520 },
      { time: '11:30', value: 22150, volume: 380 },
      { time: '12:30', value: 22300, volume: 610 },
      { time: '13:30', value: 22400, volume: 720 },
      { time: '14:30', value: 22450, volume: 850 },
    ],
  },
  {
    symbol: 'S&P 500',
    name: 'US Large Cap Index',
    price: 5120.30,
    change: 0.85,
    volume: 1250000,
    marketCap: '$44.8T',
    peRatio: 24.1,
    range52w: { low: 4103, high: 5264 },
    open: 5092.10,
    high: 5135.45,
    low: 5088.90,
    history: [
      { time: '09:30', value: 5080, volume: 1200 },
      { time: '10:30', value: 5095, volume: 1100 },
      { time: '11:30', value: 5110, volume: 950 },
      { time: '12:30', value: 5105, volume: 1400 },
      { time: '13:30', value: 5115, volume: 1300 },
      { time: '14:30', value: 5120, volume: 1550 },
    ],
  },
];

export const INDUSTRY_TRENDS: IndustryTrend[] = [
  { name: 'AI', status: 'Rising', growth: 12.5 },
  { name: 'EV', status: 'Rising', growth: 8.2 },
  { name: 'Fintech', status: 'Stable', growth: 2.1 },
  { name: 'Pharma', status: 'Falling', growth: -1.5 },
  { name: 'GenAI Video', status: 'Rising', growth: 45.2 },
  { name: 'Space Tech', status: 'Rising', growth: 18.7 },
  { name: 'Web3 Gaming', status: 'Stable', growth: 3.4 },
  { name: 'Climate Tech', status: 'Rising', growth: 22.1 },
];

export const VIRAL_TRENDS = [
  { id: 'v1', title: 'Generative AI Avatars', growth: '400%', status: '🔥 Trending Now', niche: 'Social Media', description: 'People are using AI to create high-fidelity 3D avatars for virtual meetings and content.' },
  { id: 'v2', title: 'Solar-Powered Homes', growth: '85%', status: '📈 Rising Fast', niche: 'Consumer Tech', description: 'Massive adoption of home battery backup systems like Powerwall 3.' },
  { id: 'v3', title: 'Hyper-Personalized Health', growth: '120%', status: '📈 Rising Fast', niche: 'Wellness', description: 'DNA-based nutrition plans and continuous glucose monitors for non-diabetics.' },
  { id: 'v4', title: 'Subscription Management', growth: '12%', status: '⚠️ Saturated', niche: 'SaaS', description: 'Oversupply of apps that track your other app subscriptions.' },
];

export const AI_UPDATES: AIUpdate[] = [
  {
    id: '1',
    name: 'Gemini 3.0 Ultra',
    description: 'New multimodal capabilities with long-context window up to 10M tokens released.',
    tag: 'Breakthrough',
    updatedAt: 'May 2026',
  },
  {
    id: '2',
    name: 'AutoCode Pro',
    description: 'Enterprise AI for automated codebase migrations and legacy code refactoring.',
    tag: 'Business Use',
    updatedAt: 'April 2026',
  },
  {
    id: '3',
    name: 'NeuroSynth Alpha',
    description: 'Experimental framework for bio-inspired neural architecture search.',
    tag: 'Experimental',
    updatedAt: 'April 2026',
  },
];

export const STARTUP_OPPORTUNITIES: StartupOpportunity[] = [
  {
    id: '1',
    problem: 'Excessive energy usage in office buildings after hybrid work shifts.',
    idea: 'Dynamic IoT lighting and HVAC that responds to individual smartphone location data.',
    competition: 'Low',
    relevance: 'Based on high energy costs in news.',
  },
  {
    id: '2',
    problem: 'SMEs struggling with AI governance compliance.',
    idea: 'Automated compliance-as-a-service for the new AI Governance Act.',
    competition: 'Low',
    relevance: 'Directly linked to today\'s news on AI regulation.',
  },
  {
    id: '3',
    problem: 'Increasing plastic waste in shipping materials for fragile electronics.',
    idea: 'Mycelium-based custom-molded packaging that is 100% home compostable.',
    competition: 'Medium',
    relevance: 'Follows biodiversity treaty news.',
  },
];

export const RECOMMENDED_USERS = [
  { id: 'rec-1', name: 'Marcus Aurelius', role: 'Venture Architect', match: '98%', skills: ['Investment', 'Web3'] },
  { id: 'rec-2', name: 'Diana Prince', role: 'AI Strategist', match: '95%', skills: ['LLMs', 'Prompt Engineering'] },
  { id: 'rec-3', name: 'Bruce Wayne', role: 'Operations King', match: '92%', skills: ['Supply Chain', 'Global Trade'] },
  { id: 'rec-4', name: 'Barry Allen', role: 'Growth Lead', match: '89%', skills: ['Fintech', 'SaaS'] },
];
